import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'oklch(var(--color-primary) / <alpha-value>)',
          hover: 'oklch(var(--color-primary-hover) / <alpha-value>)',
          active: 'oklch(var(--color-primary-active) / <alpha-value>)',
          subtle: 'oklch(var(--color-primary-subtle) / <alpha-value>)',
          border: 'oklch(var(--color-primary-border) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'oklch(var(--color-accent) / <alpha-value>)',
          hover: 'oklch(var(--color-accent-hover) / <alpha-value>)',
          active: 'oklch(var(--color-accent-active) / <alpha-value>)',
          subtle: 'oklch(var(--color-accent-subtle) / <alpha-value>)',
          border: 'oklch(var(--color-accent-border) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'oklch(var(--color-success) / <alpha-value>)',
          hover: 'oklch(var(--color-success-hover) / <alpha-value>)',
          subtle: 'oklch(var(--color-success-subtle) / <alpha-value>)',
          border: 'oklch(var(--color-success-border) / <alpha-value>)',
        },
        danger: {
          DEFAULT: 'oklch(var(--color-danger) / <alpha-value>)',
          hover: 'oklch(var(--color-danger-hover) / <alpha-value>)',
          subtle: 'oklch(var(--color-danger-subtle) / <alpha-value>)',
          border: 'oklch(var(--color-danger-border) / <alpha-value>)',
        },
        warning: {
          DEFAULT: 'oklch(var(--color-warning) / <alpha-value>)',
          hover: 'oklch(var(--color-warning-hover) / <alpha-value>)',
          subtle: 'oklch(var(--color-warning-subtle) / <alpha-value>)',
          border: 'oklch(var(--color-warning-border) / <alpha-value>)',
        },
        info: {
          DEFAULT: 'oklch(var(--color-info) / <alpha-value>)',
          hover: 'oklch(var(--color-info-hover) / <alpha-value>)',
          subtle: 'oklch(var(--color-info-subtle) / <alpha-value>)',
          border: 'oklch(var(--color-info-border) / <alpha-value>)',
        },
        bg: 'oklch(var(--color-bg) / <alpha-value>)',
        surface: {
          DEFAULT: 'oklch(var(--color-surface) / <alpha-value>)',
          hover: 'oklch(var(--color-surface-hover) / <alpha-value>)',
          active: 'oklch(var(--color-surface-active) / <alpha-value>)',
        },
        ink: {
          DEFAULT: 'oklch(var(--color-ink) / <alpha-value>)',
          muted: 'oklch(var(--color-ink-muted) / <alpha-value>)',
          subtle: 'oklch(var(--color-ink-subtle) / <alpha-value>)',
        },
        border: {
          DEFAULT: 'oklch(var(--color-border) / <alpha-value>)',
          strong: 'oklch(var(--color-border-strong) / <alpha-value>)',
          subtle: 'oklch(var(--color-border-subtle) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.2' }],
        '6xl': ['3.75rem', { lineHeight: '1.1' }],
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-base)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        DEFAULT: 'var(--transition-base)',
        slow: 'var(--transition-slow)',
        slower: 'var(--transition-slower)',
      },
      transitionTimingFunction: {
        'ease-in': 'var(--ease-in)',
        'ease-out': 'var(--ease-out)',
        'ease-in-out': 'var(--ease-in-out)',
        bounce: 'var(--ease-bounce)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
  plugins: [],
} satisfies Config
