import { getModeHandler, listModes } from './engine/registry.js'
import { gameConfigSchema, type GameConfig } from './game.schema.js'
import { mergeConfig, seededShuffle } from './game.util.js'
import * as repo from './game.repository.js'
import * as cache from './game.cache.js'
import { AppError } from '../../shared/errors/AppError.js'
import type { CreateGameInput, HistoryQuery, JoinGameInput } from './game.schema.js'
import type {
  GameSessionRow, HistoryEntry, HistoryPage, HistoryViewer,
  LobbyPlayer, PlayerSessionRow, SnapshotQuestion
} from './game.type.js'
import { decodeHistoryCursor, encodeHistoryCursor } from './game.history.cursor.js'
import { signSocketToken, verifySocketToken, type SocketTokenPayload } from './socket.middleware.js'
import { sanitizeConfigPatch, normalizeConfig, describeModeConfig } from './engine/config.rule.js'

// Read session: Redis first, then PostgreSQL (auto-warm cache on miss)
const loadSessionByCode = async (code: string) => {
  const gameId = await cache.getGameIdByCode(code)
  if (gameId) {
    const hit = await cache.getSession(gameId)
    if (hit) return hit
  }
  const session = await repo.getSessionByCode(code)
  if (session) await cache.setSession(session)
  return session
}

const loadSessionById = async (gameId: number) => {
  const hit = await cache.getSession(gameId)
  if (hit) return hit
  const session = await repo.getSessionById(gameId)
  if (session) await cache.setSession(session)
  return session
}

// GET /game-modes
// listModes() returns mode names, so the handler has to be looked up per mode
export const listGameModes = () =>
  listModes().map((mode) => describeModeConfig(mode, getModeHandler(mode).defaultConfig()))

// POST /games
export const createGame = async (input: CreateGameInput, hostId: number) => {
  const handler = getModeHandler(input.mode) // 400 if mode not found
  const { config, ignored } = buildConfig(input.mode, handler.defaultConfig(), input.config)

  const snapshot = await repo.createQuizSnapshot(input.quiz_id) // snapshot at the time of creation
  const session = await repo.createGameSession({
    quiz_snapshot_id: snapshot.id,
    session_name: input.session_name,
    session_host: hostId, // session_code auto-generated by repository (retry on conflict)
    game_mode: input.mode,
    config,
    total_questions: snapshot.total_questions
  })
  await cache.setSession(session) // warm cache + map session_code -> id
  return { session, ignored }
}

// GET /games/:code
export const getLobby = async (code: string) => {
  const session = await loadSessionByCode(code)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  const players: LobbyPlayer[] =
    (await cache.getPlayers(session.id)) ?? (await repo.listPlayers(session.id))
  return { session, players, config: session.config }
}

// PATCH /games/:id/config — only host, only when in lobby
export const updateGameConfig = async (
  gameId: number, hostId: number, patch: unknown
) => {
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  if (session.session_host !== hostId)
    throw new AppError(403, 'Only host can update config', 'GAME_NOT_HOST')
  if (session.session_status !== 'lobby')
    throw new AppError(409, 'Can only update config in lobby', 'GAME_LOBBY_ONLY')

  return writeConfig(session, patch)
}

// POST /games/:code/join — for both user and guest
export const joinGame = async (code: string, input: JoinGameInput) => {
  const session = await loadSessionByCode(code)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  const config = session.config

  if (session.session_status !== 'lobby' && !config.lobby.allowLateJoin)
    throw new AppError(409, 'Game already started, no late join allowed', 'GAME_ALREADY_STARTED')
  if (!input.player_id && !config.lobby.allowGuests)
    throw new AppError(403, 'Room does not allow guests', 'GAME_GUESTS_NOT_ALLOWED')
  if (input.player_id === session.session_host)
    throw new AppError(403, 'Host can not join game', 'GAME_HOST_CANNOT_JOIN')

  const currentPlayers = (await cache.countPlayers(session.id)) ?? (await repo.countPlayers(session.id))
  if ((currentPlayers ?? 0) >= config.lobby.maxPlayers)
    throw new AppError(409, 'Room is full', 'GAME_ROOM_FULL')

  let player: PlayerSessionRow | null = null
  if (input.player_id) {
    player = await repo.getPlayerSessionBySessionAndPlayer(session.id, input.player_id)
  } else if (input.player_guest_id) {
    player = await repo.getPlayerSessionBySessionAndGuest(session.id, input.player_guest_id)
  }

  if (!player) {
    player = await repo.createPlayerSession({
      game_session_id: session.id,
      player_id: input.player_id ?? null,
      player_avatar: input.player_avatar ?? null,
      player_guest_id: input.player_guest_id ?? null,
      player_name: input.player_name,
      lives: config.flow.lives ?? null // initialize lives if mode uses
    })
  }
  await cache.updatePlayer(session.id, player)

  const socketToken = signSocketToken({
    psid: player.id,
    gsid: session.id,
    code: session.session_code,
    role: 'player'
  })
  return { player, socketToken }
}

// POST /games/:id/host-token — host get token socket
export const issueHostToken = async (gameId: number, hostId: number) => {
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  if (session.session_host !== hostId)
    throw new AppError(403, 'Only host can request host token', 'GAME_NOT_HOST')

  return {
    socketToken: signSocketToken({
      psid: null,
      gsid: session.id,
      code: session.session_code,
      role: 'host'
    })
  }
}

// GET /games/:id/leaderboard — Redis ZSET when playing, fallback Postgres
export const getLeaderboard = async (gameId: number) =>
  (await cache.getLeaderboard(gameId)) ?? repo.getLeaderboard(gameId)

// GET /games/:id/results
export const getResults = async (gameId: number) => {
  // Get session meta from cache, but always read final stats from Postgres
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  return {
    session,
    leaderboard: await repo.getLeaderboard(gameId),
    perQuestion: await repo.getQuestionStats(gameId)
  }
}

// The order a player actually saw: the room order first (seeded with the room id so
// every process agrees), then the extra per-player order self-paced rooms add on top.
const questionsAsPlayed = (
  questions: SnapshotQuestion[], config: GameConfig, gameId: number, playerId: number
): SnapshotQuestion[] => {
  if (!config.flow.shuffleQuestions) return questions
  const roomOrder = seededShuffle([...questions], gameId)
  return config.flow.pacing === 'self'
    ? seededShuffle([...roomOrder], gameId + playerId)
    : roomOrder
}

const buildReview = (
  session: GameSessionRow, player: PlayerSessionRow, questions: SnapshotQuestion[]
) => {
  const ordered = questionsAsPlayed(questions, session.config, session.id, player.id)
  const total = ordered.length
  // answers are keyed by question_index: marathon loops the bank, so an index
  // can be >= total and several rows can point at the same question
  const answers = new Map(
    (player.answered_questions ?? []).map((entry) => [entry.question_index, entry] as const)
  )

  const buildItem = (q: SnapshotQuestion | undefined, index: number) => {
    const entry = answers.get(index)
    return {
      question_index: index,
      question_id: q?.id ?? entry?.question_id ?? null,
      question_text: q?.question_text ?? null,
      question_image: q?.question_image ?? null,
      answer_options: q?.answer_options ?? null,
      explanation: q?.explanation ?? null,
      // false means the player never submitted anything for this question
      answered: entry !== undefined,
      your_answer: entry ? entry.answer : null,
      correct_answer: q?.correct_answer ?? null,
      is_correct: entry?.is_correct ?? false,
      is_late: entry?.is_late ?? false,
      score_earned: entry?.score_earned ?? 0,
      time_taken: entry?.time_taken ?? null // seconds, two decimals
    }
  }

  // every question of the quiz, answered or not
  const items = ordered.map((q, index) => buildItem(q, index))
  // marathon: extra loops over the same bank keep their own rows at the end
  for (const index of Array.from(answers.keys()).sort((a, b) => a - b)) {
    if (index < total) continue
    items.push(buildItem(total > 0 ? ordered[index % total] : undefined, index))
  }

  return {
    player_score: player.player_score,
    correct_answers_count: player.correct_answers_count,
    total_questions: total,
    answered_count: answers.size,
    items,
    serverTime: new Date().toISOString()
  }
}

export const getPlayerReview = async (gameId: number, token: string | undefined) => {
  if (!token) throw new AppError(401, 'Missing socket token', 'GAME_TOKEN_INVALID')

  let payload: SocketTokenPayload
  try {
    payload = verifySocketToken(token)
  } catch {
    throw new AppError(401, 'Socket token is not valid', 'GAME_TOKEN_INVALID')
  }
  if (payload.gsid !== gameId)
    throw new AppError(403, 'Token belongs to another room', 'GAME_TOKEN_WRONG_ROOM')
  if (payload.role !== 'player' || payload.psid === null)
    throw new AppError(403, 'Only a player can review their own answers', 'GAME_PLAYER_ONLY')

  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  if (!session.config.flow.reviewMode)
    throw new AppError(403, 'Review is disabled in this room', 'GAME_REVIEW_DISABLED')
  if (session.session_status !== 'finished')
    throw new AppError(409, 'Game is still running', 'GAME_STILL_RUNNING')

  // read the player from Postgres: endGame flushes the final rows and clears the cache
  const player = await repo.getPlayerSession(payload.psid)
  if (!player || player.game_session_id !== gameId)
    throw new AppError(404, 'Player not found in this room', 'GAME_PLAYER_NOT_FOUND')

  return buildReview(session, player, await repo.getSnapshotQuestions(gameId))
}

// ---------- Play history ----------

/**
 * A closed room, read straight from Postgres.
 *
 * The cache is deliberately not consulted: endGame flushes the final rows and
 * clears it, so for a finished match the row is the truth and a warm cache entry
 * would only be a half-played copy of it.
 */
const loadClosedSession = async (gameId: number) => {
  const session = await repo.getSessionByIdIncludingDeleted(gameId)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  // Deleted is answered separately from missing: the reader had a working link and
  // deserves "this is gone" rather than "this never was".
  if (session.deleted_at) throw new AppError(410, 'Room was deleted', 'GONE')
  if (session.session_status !== 'finished' && session.session_status !== 'cancelled')
    throw new AppError(409, 'Game is still running', 'GAME_STILL_RUNNING')
  return session
}

// The reader's own player row in that match, whichever identity they carry.
const findViewerSeat = async (gameId: number, viewer: HistoryViewer) => {
  if (viewer.userId !== null) return repo.getPlayerSessionBySessionAndPlayer(gameId, viewer.userId)
  if (viewer.guestId !== null) return repo.getPlayerSessionBySessionAndGuest(gameId, viewer.guestId)
  return null
}

/**
 * Quiz identity as the history shows it.
 *
 * The snapshot holds every column of the quizzes row, ranking and lifecycle
 * columns included, so only the fields a reader is allowed to see are copied out.
 */
const snapshotQuizView = (quiz: Record<string, unknown> | null) => {
  if (!quiz) return null
  return {
    id: quiz['id'] ?? null,
    quiz_name: quiz['quiz_name'] ?? null,
    quiz_description: quiz['quiz_description'] ?? null,
    quiz_image: quiz['quiz_image'] ?? null,
    quiz_category: quiz['quiz_category'] ?? null,
    quiz_language: quiz['quiz_language'] ?? null
  }
}

// GET /games/history
export const getPlayHistory = async (
  viewer: HistoryViewer, query: HistoryQuery
): Promise<HistoryPage> => {
  const cursor = query.cursor ? decodeHistoryCursor(query.cursor, { role: query.role }) : null
  // One row past the page is read so hasMore costs nothing extra.
  const window = query.limit + 1

  let rows: HistoryEntry[]
  let total: number | undefined

  if (query.role === 'hosted') {
    // Only an account can open a room, so this tab does not exist for a guest.
    const userId = viewer.userId
    if (userId === null)
      throw new AppError(401, 'Only an account can host a room', 'GAME_AUTH_REQUIRED')
    rows = await repo.listHostedSessions(userId, cursor, window)
    if (query.include_total) total = await repo.countHostedSessions(userId)
  } else {
    if (viewer.userId === null && viewer.guestId === null)
      throw new AppError(401, 'History needs a session or a guest id', 'GAME_AUTH_REQUIRED')
    rows = await repo.listPlayedSessions(viewer, cursor, window)
    if (query.include_total) total = await repo.countPlayedSessions(viewer)
  }

  const hasMore = rows.length > query.limit
  const items = hasMore ? rows.slice(0, query.limit) : rows
  const last = items[items.length - 1]

  const page: HistoryPage = {
    items,
    hasMore,
    nextCursor: hasMore && last
      ? encodeHistoryCursor({ role: query.role, endedAt: last.ended_at, id: last.id })
      : null
  }
  if (total !== undefined) page.total = total
  return page
}

// GET /games/:id/summary — the host of the match, or anyone who played in it
export const getHistorySummary = async (gameId: number, viewer: HistoryViewer) => {
  const session = await loadClosedSession(gameId)
  const isHost = viewer.userId !== null && session.session_host === viewer.userId
  const seat = isHost ? null : await findViewerSeat(gameId, viewer)

  // A stranger gets a refusal, not the room: a session id is a small number and
  // guessing one must not hand out somebody else's match.
  if (!isHost && !seat) throw new AppError(403, 'Not part of this match', 'GAME_FORBIDDEN')

  return {
    session,
    quiz: snapshotQuizView(await repo.getSnapshotQuiz(gameId)),
    // The host always sees the full standings, exactly as in the end-of-game report.
    leaderboard: await repo.getLeaderboard(gameId),
    // Per-question accuracy describes the room rather than one player, so it stays
    // a host report.
    perQuestion: isHost ? await repo.getQuestionStats(gameId) : null,
    viewer: { isHost, playerId: seat?.id ?? null }
  }
}

/**
 * GET /games/:id/my-answers — the reader's own answer sheet, same shape as
 * GET /:id/review so one component can render both.
 *
 * The difference is the identity: review authenticates with the socket token, which
 * lives in the sessionStorage of the tab that played, so it is gone in a new tab.
 * Here the cookie or the guest id answers instead.
 */
export const getHistoryAnswers = async (gameId: number, viewer: HistoryViewer) => {
  const session = await loadClosedSession(gameId)
  const seat = await findViewerSeat(gameId, viewer)
  // A host has no answers of their own; nothing to fall back to.
  if (!seat) throw new AppError(403, 'Only a player of this match can read its answers', 'GAME_PLAYER_ONLY')
  if (!session.config.flow.reviewMode)
    throw new AppError(403, 'Review is disabled in this room', 'GAME_REVIEW_DISABLED')

  return buildReview(session, seat, await repo.getSnapshotQuestions(gameId))
}

const buildConfig = (mode: string, base: GameConfig, patch: unknown) => {
  // 1) drop everything this mode does not allow (and report it)
  const { patch: safe, ignored } = sanitizeConfigPatch(mode, patch)
  // 2) merge only the surviving fields on top of the stored config
  const merged = gameConfigSchema.parse(mergeConfig(base, safe as Partial<GameConfig>))
  // 3) rewrite what the mode owns, so the engine never reads a half-configured room
  return { config: normalizeConfig(merged, mode), ignored }
}

export const applyConfigPatchFromSocket = async (gameId: number, patch: unknown) => {
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found', 'GAME_ROOM_NOT_FOUND')
  return writeConfig(session, patch)
}

const writeConfig = async (session: GameSessionRow, patch: unknown) => {
  // the config is part of the room contract: changing it mid-game desyncs players
  if (session.session_status !== 'lobby')
    throw new AppError(409, 'Can only update config in lobby', 'GAME_LOBBY_ONLY')

  const { config, ignored } = buildConfig(session.game_mode, session.config, patch)
  // both sides went through gameConfigSchema.parse, so the key order is stable
  const changed = JSON.stringify(config) !== JSON.stringify(session.config)
  // nothing survived the filter: report it instead of rewriting the same row
  if (!changed) return { session, ignored, changed: false }

  const updated = await repo.updateSessionConfig(session.id, config)
  await cache.setSession(updated)
  return { session: updated, ignored, changed: true }
}
