import { getModeHandler, listModes } from './engine/registry.js'
import { gameConfigSchema, type GameConfig } from './game.schemas.js'
import { mergeConfig } from './game.utils.js'
import * as repo from './game.repository.js'
import * as cache from './game.cache.js'
import { AppError } from '../../shared/errors/AppError.js'
import type { CreateGameInput, JoinGameInput } from './game.schemas.js'
import type { GameSessionRow, LobbyPlayer, PlayerSessionRow } from './game.type.js'
import { signSocketToken } from './socket.middleware.js'
import { sanitizeConfigPatch, normalizeConfig, describeModeConfig } from './engine/config.rules.js'

// Read session: Redis first, then PostgreSQL (auto-warm cache on miss)
const loadSessionByCode = async (code: string) => {
  const gameId = await cache.getGameIdByCode(code)
  if (gameId) {
    const hit = await cache.getSession(gameId)
    if (hit) return hit
  }
  const session = await repo.getSessionByCode(code)
  if (session) await cache.setSession(session)
  return session
}

const loadSessionById = async (gameId: number) => {
  const hit = await cache.getSession(gameId)
  if (hit) return hit
  const session = await repo.getSessionById(gameId)
  if (session) await cache.setSession(session)
  return session
}

// GET /game-modes
// listModes() returns mode names, so the handler has to be looked up per mode
export const listGameModes = () =>
  listModes().map((mode) => describeModeConfig(mode, getModeHandler(mode).defaultConfig()))

// POST /games
export const createGame = async (input: CreateGameInput, hostId: number) => {
  const handler = getModeHandler(input.mode) // 400 if mode not found
  const { config, ignored } = buildConfig(input.mode, handler.defaultConfig(), input.config)

  const snapshot = await repo.createQuizSnapshot(input.quiz_id) // snapshot at the time of creation
  const session = await repo.createGameSession({
    quiz_snapshot_id: snapshot.id,
    session_name: input.session_name,
    session_host: hostId, // session_code auto-generated by repository (retry on conflict)
    game_mode: input.mode,
    config,
    total_questions: snapshot.total_questions
  })
  await cache.setSession(session) // warm cache + map session_code -> id
  return { session, ignored }
}

// GET /games/:code
export const getLobby = async (code: string) => {
  const session = await loadSessionByCode(code)
  if (!session) throw new AppError(404, 'Room not found')
  const players: LobbyPlayer[] =
    (await cache.getPlayers(session.id)) ?? (await repo.listPlayers(session.id))
  return { session, players, config: session.config }
}

// PATCH /games/:id/config — only host, only when in lobby
export const updateGameConfig = async (
  gameId: number, hostId: number, patch: unknown
) => {
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found')
  if (session.session_host !== hostId) throw new AppError(403, 'Only host can update config')
  if (session.session_status !== 'lobby') throw new AppError(409, 'Can only update config in lobby')

  return writeConfig(session, patch)
}

// POST /games/:code/join — for both user and guest
export const joinGame = async (code: string, input: JoinGameInput) => {
  const session = await loadSessionByCode(code)
  if (!session) throw new AppError(404, 'Room not found')
  const config = session.config

  if (session.session_status !== 'lobby' && !config.lobby.allowLateJoin)
    throw new AppError(409, 'Game already started, no late join allowed')
  if (!input.player_id && !config.lobby.allowGuests)
    throw new AppError(403, 'Room does not allow guests')
  if (input.player_id === session.session_host)
    throw new AppError(403, 'Host can not join game')

  const currentPlayers = (await cache.countPlayers(session.id)) ?? (await repo.countPlayers(session.id))
  if ((currentPlayers ?? 0) >= config.lobby.maxPlayers)
    throw new AppError(409, 'Room is full')

  let player: PlayerSessionRow | null = null
  if (input.player_id) {
    player = await repo.getPlayerSessionBySessionAndPlayer(session.id, input.player_id)
  } else if (input.player_guest_id) {
    player = await repo.getPlayerSessionBySessionAndGuest(session.id, input.player_guest_id)
  }

  if (!player) {
    player = await repo.createPlayerSession({
      game_session_id: session.id,
      player_id: input.player_id ?? null,
      player_guest_id: input.player_guest_id ?? null,
      player_name: input.player_name,
      lives: config.flow.lives ?? null // initialize lives if mode uses
    })
  }
  await cache.updatePlayer(session.id, player)

  const socketToken = signSocketToken({
    psid: player.id,
    gsid: session.id,
    code: session.session_code,
    role: 'player'
  })
  return { player, socketToken }
}

// POST /games/:id/host-token — host get token socket
export const issueHostToken = async (gameId: number, hostId: number) => {
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found')
  if (session.session_host !== hostId) throw new AppError(403, 'Only host can request host token')

  return {
    socketToken: signSocketToken({
      psid: null,
      gsid: session.id,
      code: session.session_code,
      role: 'host'
    })
  }
}

// GET /games/:id/leaderboard — Redis ZSET when playing, fallback Postgres
export const getLeaderboard = async (gameId: number) =>
  (await cache.getLeaderboard(gameId)) ?? repo.getLeaderboard(gameId)

// GET /games/:id/results
export const getResults = async (gameId: number) => {
  // Get session meta from cache, but always read final stats from Postgres
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found')
  return {
    session,
    leaderboard: await repo.getLeaderboard(gameId),
    perQuestion: await repo.getQuestionStats(gameId)
  }
}

const buildConfig = (mode: string, base: GameConfig, patch: unknown) => {
  // 1) drop everything this mode does not allow (and report it)
  const { patch: safe, ignored } = sanitizeConfigPatch(mode, patch)
  // 2) merge only the surviving fields on top of the stored config
  const merged = gameConfigSchema.parse(mergeConfig(base, safe as Partial<GameConfig>))
  // 3) rewrite what the mode owns, so the engine never reads a half-configured room
  return { config: normalizeConfig(merged, mode), ignored }
}

export const applyConfigPatchFromSocket = async (gameId: number, patch: unknown) => {
  const session = await loadSessionById(gameId)
  if (!session) throw new AppError(404, 'Room not found')
  return writeConfig(session, patch)
}

const writeConfig = async (session: GameSessionRow, patch: unknown) => {
  // the config is part of the room contract: changing it mid-game desyncs players
  if (session.session_status !== 'lobby')
    throw new AppError(409, 'Can only update config in lobby')

  const { config, ignored } = buildConfig(session.game_mode, session.config, patch)
  // both sides went through gameConfigSchema.parse, so the key order is stable
  const changed = JSON.stringify(config) !== JSON.stringify(session.config)
  // nothing survived the filter: report it instead of rewriting the same row
  if (!changed) return { session, ignored, changed: false }

  const updated = await repo.updateSessionConfig(session.id, config)
  await cache.setSession(updated)
  return { session: updated, ignored, changed: true }
}
