import { Router } from 'express'
import { authMiddleware } from '../auth/auth.middleware.js'
import { validateBody } from '../../shared/validators/validator.js'
import { presignUpload } from './storage.controller.js'
import { presignUploadSchema } from './storage.schemas.js'
import { uploadRateLimiter } from '../../shared/middlewares/rate.limit.middleware.js'

export const storageRouter: Router = Router()

/**
 * @swagger
 * /api/v1/storage/presign:
 *   post:
 *     summary: Get presigned URL for direct upload to object storage
 *     tags: [Storage]
 *     security:
 *       - cookieAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - contentType
 *               - folder
 *               - fileSize
 *             properties:
 *               contentType:
 *                 type: string
 *                 enum: [image/jpeg, image/jpg, image/png, image/gif, image/webp]
 *                 example: image/png
 *               folder:
 *                 type: string
 *                 enum: [avatars, quizzes, questions, uploads]
 *               fileSize:
 *                 type: number
 *                 description: File size limit is 2MB.
 *                 example: 1048576
 *                 minimum: 1
 *                 maximum: 2097152
 *     responses:
 *       200:
 *         description: Successfully created presigned URL. The file name will be generated by the server using UUID.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 uploadUrl:
 *                   type: string
 *                   description: URL for uploading exprires in 5 minutes
 *                 publicUrl:
 *                   type: string
 *                   description: Public URL of the file after upload
 *                 key:
 *                   type: string
 *       400:
 *         description: Invalid data
 *       401:
 *         description: Unauthorized
 */
storageRouter.post(
  '/presign',
  authMiddleware,
  uploadRateLimiter,
  validateBody(presignUploadSchema),
  presignUpload
)
